- Controller/MultidatabaseContentImportsController.php
- Model/MultidatabaseContent.php
> fix #964 (4)

- Model/MultidatabaseContent.php
- Model/MultidatabaseContentEditPr.php
Fix NetCommons3/NetCommons3/#103
> Fix NetCommons3/NetCommons3/#103

- Model/MultidatabaseContent.php
https://github.com/NetCommons3/NetCommons3/issues/1197
bugfixです。
トラビステストで問題なければ、２，３日位でマージしようと思ってます。
> fix: 汎用DBで新着登録のタイトルはvalue1以外でも対応する

- View/Helper/MultidatabaseContentViewElementHelper.php
https://github.com/NetCommons3/NetCommons3/issues/1266
バグフィックスです。
トラビステストが通ったら、マージしようと思ってます。
> fix: 画像タイプの画像幅は max-width指定にして、小さい画像を大きく表示しないようにする 

- View/Helper/MultidatabaseContentViewHelper.php
https://github.com/NetCommons3/NetCommons3/issues/1263
バグフィックスです。
トラビステストでエラーなければ、マージしようと思っています。
> fix: 選択肢（択一）で一覧画面に表示する項目OFFで、一覧に絞り込み欄非表示対応

- Model/MultidatabaseContent.php
- Model/MultidatabaseContentSearch.php
https://github.com/NetCommons3/NetCommons3/issues/1283
バグフィックスです。
トラビステストが通ったら、マージしようと思います。
> fix: 「検索の対象に含める(is_searchable)」は、全てOFFの場合もあるため、空でも例外にしない

- View/Helper/MultidatabaseContentViewElementHelper.php
https://github.com/NetCommons3/NetCommons3/issues/1235
バグフィックスです。
トラビステストが通ったら、マージしようと思います。
> fix: 日付表示ずれ対応

- View/Elements/MultidatabaseContents/view/view_content_group_c1.ctp
- View/Elements/MultidatabaseContents/view/view_content_group_c2.ctp
- View/Helper/MultidatabaseContentEditElementHelper.php
- View/Helper/MultidatabaseContentViewElementHelper.php
- webroot/css/style.css
https://github.com/NetCommons3/NetCommons3/issues/1277
https://github.com/NetCommons3/NetCommons3/issues/1184
バグフィックスです。
トラビステストが通ったら、マージしようと思ってます。
> fix: リンクは折り返し表示する 他1件

- Model/MultidatabaseMetadataEditCnv.php
https://github.com/NetCommons3/NetCommons3/issues/1285
バグ修正のちょび再修正です。（fix: 修正方法を既存のソースと合わせる）
トラビステスト通ったら、マージしようと思っています。
既存のソースの方法
https://github.com/NetCommons3/Multidatabases/blob/95872f7f717521e868ba27f7026b9815e999efa4/View/Helper/MultidatabaseContentViewHelper.php#L227
> fix: DateTime型以外の値が日付型にセットされたら、表示と編集画面では空として扱う

- View/Helper/MultidatabaseContentViewElementHelper.php
https://github.com/NetCommons3/NetCommons3/issues/1167
機能改善です。
トラビステスト通ったら、マージしようと思ってます。
> fix: リンク属性は新規ウィンドウで開くように修正

- Model/MultidatabaseContent.php
https://github.com/NetCommons3/NetCommons3/issues/1264
バグ修正です。
トラビステスト通ったら、マージしようと思ってます。
> fix: メールのリンク切れ対応 

- View/Elements/MultidatabaseContents/view/view_content_dropdown_select.ctp
- View/Elements/MultidatabaseContents/view/view_content_dropdown_sort.ctp
https://github.com/NetCommons3/NetCommons3/issues/1307
バグ修正です。
トラビステスト取ったら、マージしようと思っています。
> ソート条件や絞りこみ条件をクリア

- View/MultidatabaseContents/search_results.ctp
https://github.com/NetCommons3/NetCommons3/issues/1411
バグ修正です。
トラビステスト通ったら、マージしようと思ってます。
> fix: 検索結果で件数切替しても検索結果画面を表示する 

- Controller/MultidatabaseContentsController.php
- Model/MultidatabaseContentSearchCond.php
- View/Elements/MultidatabaseContents/view/view_content_dropdown_select.ctp
- View/Elements/MultidatabaseContents/view/view_content_dropdown_sort.ctp
https://github.com/NetCommons3/NetCommons3/issues/1467
バグ修正です。
トラビステスト通ったらマージしようと思ってます。
> fix: 一覧表示でプルダウンでソート値/チェックボックス値/セレクトボックス値を選択後、表示されたURLの値を変えると内部エラー対応

- Model/MultidatabaseContent.php
- View/Helper/MultidatabaseContentViewHelper.php
https://github.com/NetCommons3/NetCommons3/issues/1508
バグ修正です。
トラビステストを通して、問題なければマージしようと思ってます。
> bugfix: 汎用DBで多言語にした場合、英語時に登録で内部エラー対応

- Model/MultidatabaseContent.php
https://github.com/NetCommons3/NetCommons3/issues/1499
機能改善のプルリスクエストです。
トラビステストを通ったらマージしようと思ってます。
> fix: 添付ファイル項目、画像項目も、メールの投稿内容に反映する修正

- View/Helper/MultidatabaseContentViewElementHelper.php
https://github.com/NetCommons3/NetCommons3/issues/1510
機能修正のプルリクエストです。
トラビステスト通ったら、マージしようと思ってます。
> feat: ファイル項目に添付すると、表示が全てダウンロードとなる。ファイル名を表示

- Model/MultidatabaseContent.php
- Model/MultidatabaseMetadata.php
https://github.com/NetCommons3/NetCommons3/issues/1513
バグ修正のプルリクエストです。
トラビステストが通ったらマージしようと思ってます。
> bugfix: 1段目も項目なしがありえるため、0番目からループスタートに修正

- Controller/MultidatabaseContentsController.php
- Model/MultidatabaseContentSearch.php
https://github.com/NetCommons3/NetCommons3/issues/1514
バグ修正のプルリクエストです。
トラビステストが通ったら、マージしようと思ってます。
> fix: 汎用DB、ソートの降順（DB項目名＋_desc）に対応

- Model/MultidatabaseContent.php
https://github.com/researchmap/RmNetCommons3/issues/1619
> fix: 移行では、keyカラムにランダムの値がセットされるため追加ができないためmultidatabase_idで処理するように修正

- Model/MultidatabaseContent.php
https://github.com/researchmap/RmNetCommons3/issues/1619
> fix: debugの消し忘れ。

- View/Helper/MultidatabaseContentViewElementHelper.php
https://github.com/NetCommons3/NetCommons3/issues/1552
> fix: ダウンロードPWがないときに、ダウンロード回数が表示されないバグ修正

- View/Helper/MultidatabaseContentViewElementHelper.php
https://github.com/researchmap/RmNetCommons3/issues/1715
> fix: 添付ファイルを差し替えたら、ダウンロード回数がクリアされてしまうバグ修正

- .travis.yml
https://github.com/NetCommons3/NetCommons3/issues/1560
> change: test: travis.ymlからphp5.4,5.5を削除。php7.3,7.4を追加

- webroot/css/style.css
連続した半角英数字を入力されても適切に折り返すようにCSS定義追加
> refs : NetCommons3/NetCommons3/issues/1507
